[package]
name    = "wifi"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Gasquez <sergio.gasquez@gmail.com>"]

[dependencies]
anyhow      = { workspace = true }
esp-idf-svc = { workspace = true }
log         = { workspace = true }

[build-dependencies]
embuild = { workspace = true }

[dev-dependencies]
toml-cfg = { workspace = true }
