[package]
name    = "rgb-led"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Gasquez <sergio.gasquez@gmail.com>"]

[dependencies]
anyhow      = { workspace = true }
esp-idf-svc = { workspace = true }
esp-idf-hal ={ version = "=0.45.0", features = ["rmt-legacy"] }
log         = { workspace = true }
rgb         = { workspace = true }

[build-dependencies]
embuild = { workspace = true }
