[mqtt]
mqtt_host = "test.mosquitto.org"
wifi_ssid = "1107"
wifi_psk = "bigmoney1"

# If you're participating in a Ferrous Systems training, 
# login credentials for a server operated by Espressif 
# will be made available in the workshop.

# If you are working on your own you could use one listed at https://test.mosquitto.org/,
# e.g. the simplest way is to just place `mqtt_host = "test.mosquitto.org"` (and remove the other mqtt keys but leave the wifi ones).

